apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evs-gpssd2-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: evs-sc-gpssd2
