apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-sc-gpssd2
provisioner: evs.csi.huaweicloud.com
allowVolumeExpansion: true
parameters:
  type: GPSSD2
  iops: "4000"
  throughput: "200"
reclaimPolicy: Delete
