apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-evs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-evs